//This file is automatically generated by generator.lua from https://github.com/gucio321/cimguizmo
//based on ImGuizmo.h file version XXX from ImGuizmo https://github.com/CedricGuillemet/ImGuizmo

#include "./imguizmo/ImGuizmo.h"
#include "cimguizmo.h"


